import type { Card } from './types';

/** 机会卡 id: 0-15, 宝箱卡 id: 100-115。效果同经典版, 文案加拿大风味 */
export const CHANCE_CARDS: Card[] = [
  {
    id: 0,
    deck: 'chance',
    text: '前进到起点, 领取 $200',
    textEn: 'Advance to GO and collect $200',
    textFr: 'Avancez à Départ et recevez 200 $',
    effect: { kind: 'move-to', tileId: 0 },
  },
  {
    id: 1,
    deck: 'chance',
    text: '前进到蒙特利尔 Montreal',
    textEn: 'Advance to Montreal',
    textFr: 'Avancez à Montréal',
    effect: { kind: 'move-to', tileId: 24 },
  },
  {
    id: 2,
    deck: 'chance',
    text: '前进到温哥华 Vancouver',
    textEn: 'Advance to Vancouver',
    textFr: 'Avancez à Vancouver',
    effect: { kind: 'move-to', tileId: 37 },
  },
  {
    id: 3,
    deck: 'chance',
    text: '前进到里贾纳 Regina',
    textEn: 'Advance to Regina',
    textFr: 'Avancez à Regina',
    effect: { kind: 'move-to', tileId: 11 },
  },
  {
    id: 4,
    deck: 'chance',
    text: '前进到最近的铁路。若已有主人, 付双倍租金; 若无主, 可以购买',
    textEn: 'Advance to the nearest railroad. If owned, pay double rent; if unowned, you may buy it',
    textFr: 'Avancez au chemin de fer le plus proche. S’il est possédé, payez le double du loyer; sinon, vous pouvez l’acheter',
    effect: { kind: 'move-nearest', target: 'railroad' },
  },
  {
    id: 5,
    deck: 'chance',
    text: '前进到最近的铁路。若已有主人, 付双倍租金; 若无主, 可以购买',
    textEn: 'Advance to the nearest railroad. If owned, pay double rent; if unowned, you may buy it',
    textFr: 'Avancez au chemin de fer le plus proche. S’il est possédé, payez le double du loyer; sinon, vous pouvez l’acheter',
    effect: { kind: 'move-nearest', target: 'railroad' },
  },
  {
    id: 6,
    deck: 'chance',
    text: '前进到最近的公用事业。若已有主人, 掷骰子付点数 10 倍的费用',
    textEn: 'Advance to the nearest utility. If owned, roll the dice and pay 10 times the total',
    textFr: 'Avancez au service public le plus proche. S’il est possédé, lancez les dés et payez 10 fois le total',
    effect: { kind: 'move-nearest', target: 'utility' },
  },
  {
    id: 7,
    deck: 'chance',
    text: '银行派发股息, 收 $50',
    textEn: 'The bank pays a dividend. Collect $50',
    textFr: 'La banque verse un dividende. Recevez 50 $',
    effect: { kind: 'money', amount: 50 },
  },
  {
    id: 8,
    deck: 'chance',
    text: '出狱卡 — 保留到需要时使用',
    textEn: 'Get Out of Jail Free - keep until needed',
    textFr: 'Carte Libéré de prison - gardez-la jusqu’au besoin',
    effect: { kind: 'jail-card' },
  },
  {
    id: 9,
    deck: 'chance',
    text: '后退 3 格',
    textEn: 'Go back 3 spaces',
    textFr: 'Reculez de 3 cases',
    effect: { kind: 'move-back', steps: 3 },
  },
  {
    id: 10,
    deck: 'chance',
    text: '直接入狱! 不经过起点, 不领 $200',
    textEn: 'Go directly to Jail! Do not pass GO, do not collect $200',
    textFr: 'Allez directement en prison! Ne passez pas par Départ, ne recevez pas 200 $',
    effect: { kind: 'go-to-jail' },
  },
  {
    id: 11,
    deck: 'chance',
    text: '冬季风暴! 房屋维修: 每栋房 $25, 每座酒店 $100',
    textEn: 'Winter storm! Property repairs: $25 per house, $100 per hotel',
    textFr: 'Tempête hivernale! Réparations: 25 $ par maison, 100 $ par hôtel',
    effect: { kind: 'repairs', perHouse: 25, perHotel: 100 },
  },
  {
    id: 12,
    deck: 'chance',
    text: '401 高速上超速, 罚款 $15',
    textEn: 'Speeding on Highway 401. Pay $15',
    textFr: 'Excès de vitesse sur l’autoroute 401. Payez 15 $',
    effect: { kind: 'money', amount: -15 },
  },
  {
    id: 13,
    deck: 'chance',
    text: '乘 VIA 铁路旅行, 前进到 VIA 铁路 (经过起点领 $200)',
    textEn: 'Take VIA Rail to VIA Rail. Collect $200 if you pass GO',
    textFr: 'Prenez VIA Rail jusqu’à VIA Rail. Recevez 200 $ si vous passez par Départ',
    effect: { kind: 'move-to', tileId: 5 },
  },
  {
    id: 14,
    deck: 'chance',
    text: '你当选业主委员会主席, 付给每位玩家 $50',
    textEn: 'You are elected chair of the owners’ association. Pay each player $50',
    textFr: 'Vous êtes élu président du comité des propriétaires. Payez 50 $ à chaque joueur',
    effect: { kind: 'money-each', amount: -50 },
  },
  {
    id: 15,
    deck: 'chance',
    text: '你的建房贷款获批, 收 $150',
    textEn: 'Your construction loan is approved. Collect $150',
    textFr: 'Votre prêt de construction est approuvé. Recevez 150 $',
    effect: { kind: 'money', amount: 150 },
  },
];

export const CHEST_CARDS: Card[] = [
  {
    id: 100,
    deck: 'chest',
    text: '回到起点, 领取 $200',
    textEn: 'Return to GO and collect $200',
    textFr: 'Retournez à Départ et recevez 200 $',
    effect: { kind: 'move-to', tileId: 0 },
  },
  {
    id: 101,
    deck: 'chest',
    text: '银行算错汇率, 你多收 $200',
    textEn: 'The bank miscalculated the exchange rate. Collect $200',
    textFr: 'La banque a mal calculé le taux de change. Recevez 200 $',
    effect: { kind: 'money', amount: 200 },
  },
  {
    id: 102,
    deck: 'chest',
    text: '诊所挂号费, 付 $50',
    textEn: 'Clinic appointment fee. Pay $50',
    textFr: 'Frais de clinique. Payez 50 $',
    effect: { kind: 'money', amount: -50 },
  },
  {
    id: 103,
    deck: 'chest',
    text: '自家枫糖浆卖爆了, 收 $50',
    textEn: 'Your maple syrup stand sells out. Collect $50',
    textFr: 'Votre sirop d’érable maison se vend très bien. Recevez 50 $',
    effect: { kind: 'money', amount: 50 },
  },
  {
    id: 104,
    deck: 'chest',
    text: '出狱卡 — 保留到需要时使用',
    textEn: 'Get Out of Jail Free - keep until needed',
    textFr: 'Carte Libéré de prison - gardez-la jusqu’au besoin',
    effect: { kind: 'jail-card' },
  },
  {
    id: 105,
    deck: 'chest',
    text: '直接入狱! 不经过起点, 不领 $200',
    textEn: 'Go directly to Jail! Do not pass GO, do not collect $200',
    textFr: 'Allez directement en prison! Ne passez pas par Départ, ne recevez pas 200 $',
    effect: { kind: 'go-to-jail' },
  },
  {
    id: 106,
    deck: 'chest',
    text: '度假基金到期, 收 $100',
    textEn: 'Vacation fund matures. Collect $100',
    textFr: 'Votre fonds de vacances arrive à échéance. Recevez 100 $',
    effect: { kind: 'money', amount: 100 },
  },
  {
    id: 107,
    deck: 'chest',
    text: 'CRA 给你退税, 收 $20',
    textEn: 'CRA sends a tax refund. Collect $20',
    textFr: 'L’ARC vous envoie un remboursement d’impôt. Recevez 20 $',
    effect: { kind: 'money', amount: 20 },
  },
  {
    id: 108,
    deck: 'chest',
    text: '今天是你的生日, 每位玩家给你 $10',
    textEn: 'It is your birthday. Each player gives you $10',
    textFr: 'C’est votre anniversaire. Chaque joueur vous donne 10 $',
    effect: { kind: 'money-each', amount: 10 },
  },
  {
    id: 109,
    deck: 'chest',
    text: '人寿保险分红, 收 $100',
    textEn: 'Life insurance dividend. Collect $100',
    textFr: 'Dividende d’assurance vie. Recevez 100 $',
    effect: { kind: 'money', amount: 100 },
  },
  {
    id: 110,
    deck: 'chest',
    text: '牙医账单 (医保不包!), 付 $100',
    textEn: 'Dentist bill, not covered. Pay $100',
    textFr: 'Facture de dentiste, non couverte. Payez 100 $',
    effect: { kind: 'money', amount: -100 },
  },
  {
    id: 111,
    deck: 'chest',
    text: '孩子冰球夏令营报名费, 付 $50',
    textEn: 'Kids’ hockey camp registration. Pay $50',
    textFr: 'Inscription au camp de hockey des enfants. Payez 50 $',
    effect: { kind: 'money', amount: -50 },
  },
  {
    id: 112,
    deck: 'chest',
    text: '周末帮邻居铲雪, 收 $25',
    textEn: 'Weekend snow shoveling for a neighbor. Collect $25',
    textFr: 'Déneigement du week-end chez un voisin. Recevez 25 $',
    effect: { kind: 'money', amount: 25 },
  },
  {
    id: 113,
    deck: 'chest',
    text: '街道除冰翻修: 每栋房 $40, 每座酒店 $115',
    textEn: 'Street de-icing repairs: $40 per house, $115 per hotel',
    textFr: 'Travaux de déglaçage de rue: 40 $ par maison, 115 $ par hôtel',
    effect: { kind: 'repairs', perHouse: 40, perHotel: 115 },
  },
  {
    id: 114,
    deck: 'chest',
    text: '枫糖节烘焙比赛第二名, 收 $10',
    textEn: 'Maple festival bake-off runner-up. Collect $10',
    textFr: 'Deuxième place au concours de pâtisserie du festival de l’érable. Recevez 10 $',
    effect: { kind: 'money', amount: 10 },
  },
  {
    id: 115,
    deck: 'chest',
    text: '收到远房亲戚的遗产, 收 $100',
    textEn: 'Inheritance from a distant relative. Collect $100',
    textFr: 'Héritage d’un parent éloigné. Recevez 100 $',
    effect: { kind: 'money', amount: 100 },
  },
];

const ALL_CARDS = new Map<number, Card>([...CHANCE_CARDS, ...CHEST_CARDS].map((c) => [c.id, c]));

export function getCard(id: number): Card {
  const card = ALL_CARDS.get(id);
  if (!card) throw new Error(`unknown card ${id}`);
  return card;
}
